name: default

kind: pipeline
type: docker
os: linux

platform:
  arch: arm64

steps:
- name: greeting
  image: alpine
  commands:
  - pwd
  - date
  - hostname
  - echo $HOME

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --recursive --remote

- name: build
  image: ubuntu
  settings:
     repo: docker-http-server
     create_repository: true
     registry: 565683576536.dkr.ecr.eu-west-1.amazonaws.com
     access_key:
       from_secret: ecr-sx-aws_access_key_id
     secret_key:
       from_secret: ecr-sx-aws_secret_access_key
     region: eu-west-1
  tags: 
    - 1.0.0

#- name: slack
#  image: plugins/slack
#  settings:
#    webhook:
#      from_secret: slack_webhook
#    channel: meerkat-ci
#  when:
#    status: [ success, failure ]

- name: notify
  image: igal/drone-email
  environment:
   email_api_key:
     from_secret: google_email_api_key
  settings:
    host: smtp.gmail.com
    port: 587
    skip_verify: false
    from: cicd@sightx.ai
    username: cicd-SX
    password: email_api_key
    recipients:
      - igal@sightx.ai


node:
  cloud: yes
  arch: arm64
