name: default

kind: pipeline
type: docker
os: linux

platform:
  arch: arm64

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - touch /tmp/test
  - pwd
  - ls -lrt 
  - date
  - sleep 5m
  - hostname
  - echo $HOME

- name: build
  image: plugins/ecr:linux-arm64
  settings:
     repo: docker-http-server
     create_repository: true
     registry: 565683576536.dkr.ecr.eu-west-1.amazonaws.com
     access_key:
       from_secret: ecr-sx-aws_access_key_id
     secret_key:
       from_secret: ecr-sx-aws_secret_access_key
  tags: 
    - 1.0.0
    - 1.0
    - latest
